[workspace]

members = [
    "echo",
    "primes_service",
    "time_price",
    "budget_chat",
    "unusual_db",
    "mob_in_the_middle",
    "netcrab",
    "speedd_clients",
    "speedd_codecs",
    "speedd",
]
