[workspace]

members = [
    "budget_chat",
    "echo",
    "line_reversal",
    "lrcp_client",
    "lrcp_codec",
    "mob_in_the_middle",
    "netcrab",
    "primes_service",
    "speedd",
    "speedd_benchy",
    "speedd_clients",
    "speedd_codecs",
    "time_price",
    "unusual_db",
]
