[package]
name = "time_price"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
bytes = "1.4.0"
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
