[package]
name = "budget_chat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
futures = "0.3.31"
itertools = "0.10.5"
tokio = { version = "1.41.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["codec"] }
