[package]
name = "lrcp_codec"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
bytes = "1.4.0"
tokio-util = { version = "0.7.7", features = ["codec", "net"] }
serde = { version = "1", features = ["derive"] }
log = "0.4.17"
regex = "1.7.1"
once_cell = "1.17.1"
