[package]
name = "lrcp_codec"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bytes = "1.8.0"
log = "0.4.22"
once_cell = "1.20.2"
regex = "1.11.1"
serde = { version = "1", features = ["derive"] }
tokio-util = { version = "0.7.12", features = ["codec", "net"] }
