[package]
name = "mob_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
bytes = "1.4.0"
futures = "0.3.26"
lazy_static = "1.4.0"
regex = "1.7.1"
tokio = { version = "1.25.0", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
