[package]
name = "speedd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
bytes = "1.4.0"
futures = "0.3.26"
itertools = "0.10.5"
lazy_static = "1.4.0"
tokio = { version = "1.25.0", features = ["full"] }
tokio-stream = "0.1.11"
tokio-test = "0.4.2"
tokio-util = { version = "0.7.4", features = ["codec"] }
